---
- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v2
  with:
    token: ${{ secrets.PAT }}
    repository: username/my-repo
    event-type: my-event
    client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
