name: Ping
env:
  owner: Bonny5171
  repo: League_of_Legends
on:
  repository_dispatch:
    types: [run-ping]
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master