name: Release & Publish via NPM V2

on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checa o codigo
        uses: actions/checkout@v2
   
      - name: Install packages
        run: npm ci

      - name: Inicializa usuario Git
        run: |
            git config --global user.email "actions@cognyhub.com"
            git config --global user.name "Actions Release Workflow"

      - name: Inicializa o NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: End message
        run: echo 'All done!'