name: Release & Publish via NPM
env:
  owner: Bonny5171
  repo: League_of_Legends
on:
  repository_dispatch:
    types: [run-release]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Bonny5171/League_of_Legends
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Install packages
        run: npm ci

      - name: Inicializa usuario Git
        run: |
            git config --global user.email "actions@cognyhub.com"
            git config --global user.name "Actions Release Workflow"

      - name: Run release
        run: npm run release --ci

      - name: End message
        run: echo 'All done!'
